### ISSUE TITLE
Reward Ad not found on Facebook Audience Network

### ISSUE THREAD

**Issue by shinewanna** [dreamsoftin/facebook_audience_network#101]
![Screen Shot 2021-04-14 at 2 41 00 PM](https://user-images.githubusercontent.com/39454969/114676768-a7d96c80-9d2f-11eb-9e1a-277b13085631.png)

I want to add reward ad, there's no Reward Ad in fb audience. What should i choose?

**Comment by adriancsbna** [comment]
Hello @shinewanna 

It may be because Facebook only allows RewardedAds in games, so if you have not put your App in the store as a game it will not appear.
