### ISSUE TITLE
Banner does not refresh

### ISSUE THREAD

**Issue by AlakbarHeyderov** [dreamsoftin/facebook_audience_network#102]
When the page is opened, the banner comes up.  Even if you stay on the same page for 1 hour, the banner is not refreshed.  Facebook support team is working very badly. They don't answer questions.  The video below has a detailed recording

I want to show a new ad every 1 minute.

I would be grateful if you could help

https://www.youtube.com/watch?v=OiPUVye_79E

**Comment by briankariuki** [comment]
Same case, banner does not refresh

**Comment by SachinGanesh** [comment]
> Ad refresh is not supported by Facebook Audience Network.

https://developers.facebook.com/docs/audience-network/support/faq/

You can refer this #28
