### ISSUE TITLE
Need "null-safety"

### ISSUE THREAD

**Issue by AleXoTroN** [dreamsoftin/facebook_audience_network#108]
Dear developers of the package.

I wish you can make the package ready for null safety because many devs are migrating their apps to null safety and we cannot longer use the facebook audience network package.

Best wishes,
Alex

**Comment by kellvembarbosa** [comment]
UP

**Comment by rakib205** [comment]
up

**Comment by SachinGanesh** [comment]
Release null-safety version https://pub.dev/packages/facebook_audience_network/versions/1.0.0-nullsafety.0
