### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependenciesdon't support null safety: - package:facebook_audience_network

### ISSUE THREAD

**Issue by sheribaloch** [dreamsoftin/facebook_audience_network#110]
Please suggest a solution

**Comment by SachinGanesh** [comment]
Are you using the latest version of the package?

**Comment by sheribaloch** [comment]
yes . facebook_audience_network: ^0.9.0

**Comment by SachinGanesh** [comment]
Null safety is already available as a preview package https://pub.dev/packages/facebook_audience_network/versions/1.0.0-nullsafety.0
