### ISSUE TITLE
Could not resolve com.facebook.android:audience-network-sdk:6.+. Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by pradeepsthapa** [dreamsoftin/facebook_audience_network#130]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:audience-network-sdk:6.+.
     Required by:
         project :app > project :facebook_audience_network
      > Failed to list versions for com.facebook.android:audience-network-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/audience-network-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/audience-network-sdk/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by damonaskavio** [comment]
Specifying a specific version for the SDK seems to have done the trick for me

```app/build.gradle```

```
dependencies {
     ...

    constraints {
        implementation('com.facebook.android:audience-network-sdk') {
            version {
                strictly '6.8.0'
            }
    }
  }
}
```

**Comment by yutikgithub** [comment]
not work in my project.

**Comment by yutikgithub** [comment]
any other solution?
