### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by MonuKumar0** [dreamsoftin/facebook_audience_network#14]
build failing on running app with following error:

Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'com.google.android.exoplayer:exoplayer-dash:r2.4.2' is set to compileOnly/provided which is not supported

**Comment by SurajShettigar** [comment]
Can you show the entire gradle error log?

**Comment by MonuKumar0** [comment]
Actually I was using some other plugin for Facebook audience network. After removing that, everything works fine.
