### ISSUE TITLE
Rewarded Ad: RewardedVideoAdResult.ERROR

### ISSUE THREAD

**Issue by satyapsr13** [dreamsoftin/facebook_audience_network#142]
>> Facebook Audiance Network  >> Rewarded Ad: RewardedVideoAdResult.ERROR --> 
{
**error_message**:  The display format in the ad request does not match the display format specified for this placement. 
                          Each placement can only be used with a single display format. You can create multiple placements in order to use multiple display formats.,

 **error_code**: 1203, 

**invalidated**: true, 

**placement_id**: 1443383636195474_1444181286115709
}

How to solve this problem.

**Comment by itsvivek-in** [comment]
Hi, did you manage to solve it? It is happening with me as well? I double-checked and the placement id and ad format, both are correct.

**Comment by satyapsr13** [comment]
Instead of facebook ads i shifted to Admob.
