### ISSUE TITLE
Got error verifyReleaseResources when trying to build release apk #844

### ISSUE THREAD

**Issue by istiaksaif** [dreamsoftin/facebook_audience_network#153]
:facebook_audience_network:verifyReleaseResources'.

A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
Android resource linking failed
ERROR:/home/istaiksaif/Documents/Sports76/build/facebook_audience_network/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

**Comment by DevanshiGor** [comment]
I am also facing the same issue with Flutter 3.24.x...
Please suggestion some workaround.
Thanks in advance !!

**Comment by Alvish0407** [comment]
try adding the code block highlighted below to the `android/build.gradle` file in your project directory.

```diff
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
+    afterEvaluate {
+        android {
+            compileSdkVersion 34
+        }
+    }
}
```

**Comment by istiaksaif** [comment]
Try this workaround:

Change (at android/build.gradle):

```
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
```
To:

```
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}
```


**The solution currently works. flutter version 3.24.3**

**Comment by shamimcse1** [comment]
I just wanted to take a moment to thank you for helping me resolve the verifyReleaseResources error during the release build process. Your assistance was invaluable, and I truly appreciate the time you took to guide me through it.

Thanks again for your support! I look forward to working with you in the future.

**Comment by shamimcse1** [comment]
@istiaksaif I just wanted to take a moment to thank you for helping me resolve the verifyReleaseResources error during the release build process. Your assistance was invaluable, and I truly appreciate the time you took to guide me through it.

Thanks again for your support! I look forward to working with you in the future.
