### ISSUE TITLE
Banner Ad: BannerAdResult.ERROR --> {error_message: No fill, error_code: 1001, invalidated: true, placement_id: YOUR_PLACEMENT_ID} 

### ISSUE THREAD

**Issue by Hendaru** [dreamsoftin/facebook_audience_network#21]
I have error like this ' Banner Ad: BannerAdResult.ERROR --> {error_message: No fill, error_code: 1001, invalidated: true, placement_id: YOUR_PLACEMENT_ID} ' pleace help me..

**Comment by SurajShettigar** [comment]
No fill error is server sided. Try testing your app with testIDs, follow this [link](https://developers.facebook.com/docs/audience-network/testing/) on how to do it.

**Comment by erperejildo** [comment]
@SurajShettigar how to get the device ID? That link doesn't explain how

**Comment by SrashtaSoftMobileApp** [comment]
@erperejildo 

To find your device’s advertising ID:

• Android devices – To find your Google advertising ID (GAID), open the Settings app on your Android device, click on Google, and then select “Ads” under Services. Your GAID will be listed at the bottom of the screen.

• iOS devices (iPhones, iPads) – Unfortunately iOS does not provide a way for you to see your device’s advertising ID (IDFA). There are some free third-party apps available in the App Store that will display your IDFA. Below is a list of apps published by the mobile measurement partners (MMP) that we and our advertisers work with:

Adjust Insights, by Adjust
My Device ID, by AppsFlyer
Branch – Device ID Finde‪r, by Branch
My Device Identifier‪s‬, by Kochava
Singular Device Assist, by Singular
