### ISSUE TITLE
refresh native banner ads

### ISSUE THREAD

**Issue by duduf15** [dreamsoftin/facebook_audience_network#23]
I use the native banner, is it possible to refresh the ads as on admob? Because my advertising is never refreshed, which limits the number of printing.
Thank You

**Comment by SachinGanesh** [comment]
> Ad refresh is not supported by Facebook Audience Network.

[https://developers.facebook.com/docs/audience-network/support/faq/](https://developers.facebook.com/docs/audience-network/support/faq/)
