### ISSUE TITLE
Unable to refresh Banner Ad

### ISSUE THREAD

**Issue by JohnBaker123** [dreamsoftin/facebook_audience_network#28]
How to refresh Banner ads?  I am trying to just set previous instance of FacebookBannerAd to null create a new instance of FacebookBannerAd since it looks like the banner doesn't get refreshed on there own. But none of the listener events are getting triggered on the 2nd instance so I am not seeing it loading.

FacebookBannerAd(
    placementId: "YOUR_PLACEMENT_ID",
    bannerSize: BannerSize.STANDARD,
    listener: (result, value) {
      switch (result) {
        case BannerAdResult.ERROR:
          print("Error: $value");
          break;
        case BannerAdResult.LOADED:
          print("Loaded: $value");
          break;
        case BannerAdResult.CLICKED:
          print("Clicked: $value");
          break;
        case BannerAdResult.LOGGING_IMPRESSION:
          print("Logging Impression: $value");
          break;
      }
    },
  ),

**Comment by JohnBaker123** [comment]
Ignore this. I seems to work now. 

In my loaded listener if I put a few delays in there it seems to reload correctly. So I clear the banner for 1 second and then display the new instance.

                    } else if (result == BannerAdResult.LOADED) {
                      setState(() {
                        _showBannerAd = true;
                      });
                      await new Future.delayed(const Duration(seconds: 90));
                      setState(() {
                        fb_banner_ad = null;
                      });
                      await new Future.delayed(const Duration(seconds: 1));
                      createFacebookBanner();

**Comment by therichiekumar** [comment]
Hey @JohnBaker123, Can you please provide full source code. I can't understand somethings you mentioned above.

**Comment by bettkipronoh** [comment]
@JohnBaker123  how did you handle this? Am facing the same issue
