### ISSUE TITLE
ads does not show in Release apk in android

### ISSUE THREAD

**Issue by MBugOnYou** [dreamsoftin/facebook_audience_network#29]
Hope all is well.

I understand you are having some issues with your Android property and Ads status stuck in Idle.

After having a look into your account, I can confirm that the reason traffic has been stopped on your property is because your **Android SDK is currently running an outdated and unsupported version**.

We kindly ask you to update your Android SDK in order to receive Ads traffic on your platform.

Best regards,

George
Facebook Partners Support Analyst

**Comment by dipinarora9** [comment]
The plug-in is now updated to latest version.
