### ISSUE TITLE
Server Issue [iOS Platform]

### ISSUE THREAD

**Issue by iamar1k92** [dreamsoftin/facebook_audience_network#37]
I got server issue when integrating git dependency block in pubspec.yaml file. 
Any help will be appreciated. Thanks!!

**Comment by SachinGanesh** [comment]
Please share error log here

**Comment by iamar1k92** [comment]
well, i don't have mac access. At the moment, can i share the source code? It is very single one screen flutter app..

**Comment by iamar1k92** [comment]
Pubspec.yaml: 
name: uphatter
description: A flutter webview by UPHATTER.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_inappwebview: ^3.0.0
  facebook_audience_network:
    git:
      url: git@github.com:dreamsoftin/facebook_audience_network.git
      ref: ios



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

**Comment by iamar1k92** [comment]
/Users/ahsanimran/Downloads/flutter/bin/flutter --no-color packages get
Waiting for another flutter command to release the startup lock...
Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/ahsanimran/Downloads/flutter
  previous reference  : /home/amar/flutter
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been mounted at a different location. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

Running "flutter pub get" in Uphatter-master...                 
Git error. Command: `git clone --mirror git@github.com:dreamsoftin/facebook_audience_network.git /Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb`

stdout: 

stderr: Cloning into bare repository '/Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb'...

Host key verification failed.

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Git error. Command: `git clone --mirror git@github.com:dreamsoftin/facebook_audience_network.git /Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb`

stdout: 

stderr: Cloning into bare repository '/Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb'...

Host key verification failed.

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

Git error. Command: `git clone --mirror git@github.com:dreamsoftin/facebook_audience_network.git /Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb`

stdout: 

stderr: Cloning into bare repository '/Users/ahsanimran/Downloads/flutter/.pub-cache/git/cache/facebook_audience_network-d4d4259ce22ce45e5bd7ac76cce4e0e4514f9bfb'...

Host key verification failed.

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128

pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...

**Comment by SachinGanesh** [comment]
Try this url `https://github.com/dreamsoftin/facebook_audience_network.git` instead of git@

**Comment by iamar1k92** [comment]
I tried, i have added public key in my github settings. I was able to fetch the plugin in pubsec.yaml. Many Thanks!

**Comment by casualcoder404** [comment]
> I tried, i have added public key in my github settings. I was able to fetch the plugin in pubsec.yaml. Many Thanks!

@iamar1k92 were you able to implement ads?

**Comment by iamar1k92** [comment]
i am not .
