### ISSUE TITLE
Version 0.6.0 iOS not building

### ISSUE THREAD

**Issue by davidBarbieri** [dreamsoftin/facebook_audience_network#38]
Hi, thanks for this great plugin.

I used the git version for IOS and it was working correctly, i updated now to version 0.6.0 but can't get the build to work. i tried with `pod deintegrate` `pod update`, deleting the pods folder, podfile.lock, but to no avail.

The error i get is:

`
=== BUILD TARGET facebook_audience_network OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/davidbarbieri/development/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_audience_network-0.6.0/ios/Classes/FacebookAudienceNetworkPlugin.m:3:9: fatal error: 'facebook_audience_network-Swift.h' file not found
    #import "facebook_audience_network-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
`

Thanks!

**Comment by linsvensson** [comment]
I'm having the same problem, except I didn't try the git version.

**Comment by casualcoder404** [comment]
Yes I'm experiencing the same issue

Xcode shows:
Lexical or Preprocessor issue:
'facebook_audience_network-Swift.h' file not found

**Comment by SachinGanesh** [comment]
Hi, Please check the version 0.6.1

**Comment by linsvensson** [comment]
It's working for me now, thanks!

**Comment by Vasantika20** [comment]
I tried both versions 0.6.1 and 0.6.2 but still getting this error. what should i do?

**Comment by SachinGanesh** [comment]
Try `flutter clean` or delete `pubspec.lock` file

**Comment by Vasantika20** [comment]
Thank you for your response. I tried both flutter clean and delete pubsec.lock, but still getting error.

flutter/.pub-cache/hosted/pub.dartlang.org/facebook_audience_network-0.6.2/ios/Classes/FacebookAudienceNetworkPlugin.m:2:9: fatal error: 'facebook_audience_network/facebook_audience_network-Swift.h' file not found
    #import <facebook_audience_network/facebook_audience_network-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
