### ISSUE TITLE
iOS Integration Issue

### ISSUE THREAD

**Issue by DanielSmith1239** [dreamsoftin/facebook_audience_network#40]
I really appreciate the work being put in to allow for iOS integration, but I'm running into a bit of an issue that's preventing my project from running. When I try to run the project, the following error is printed to the console: 

    Launching lib/main.dart on iPhone 11 Pro in debug mode...
    Running pod install...                                              1.0s
    CocoaPods' output:
    ↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `connectivity_macos` from `.symlinks/plugins/connectivity_macos/ios`
    -> Fetching podspec for `facebook_audience_network` from `.symlinks/plugins/facebook_audience_network/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "facebook_audience_network":
      In Podfile:
        facebook_audience_network (from `.symlinks/plugins/facebook_audience_network/ios`)
    Specs satisfying the `facebook_audience_network (from `.symlinks/plugins/facebook_audience_network/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/bin/pod:23:in `load'
    /Users/danielsmith/.rvm/rubies/ruby-2.4.6/bin/pod:23:in `<main>'
    /Users/danielsmith/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
    /Users/danielsmith/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
    Error output from CocoaPods:
    ↳
    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
    Error running pod install
    Error launching application on iPhone 11 Pro.
    Exited (sigterm)

**Comment by SachinGanesh** [comment]
As mentioned in the doc, please update the target platform in podfile to 9.0. You can refer the example app

**Comment by ch-muhammad-adil** [comment]
Facing same issue 
i have set target platform to 10 in the podfile, even tried with 9.0 as well. I guess you have to update the pod version in plugin? @SachinGanesh  

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.4.0)
Installing BoringSSL-GRPC (0.0.7)
Installing FBAudienceNetwork (5.8.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/r2/4tpswhsd7f54rn050dw1dm740000gn/T/d20200711-8060-fonx37/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.8.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:13 --:--:--     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

```

**Comment by ch-muhammad-adil** [comment]
What i have found in 5.9.0 version it is working fine. So if you can please update it now? My project update is blocked because of this issue. Thanks.

**Comment by ch-muhammad-adil** [comment]
https://github.com/dreamsoftin/facebook_audience_network/blob/master/ios/facebook_audience_network.podspec 
@SachinGanesh So here it has issue. The latest version of SDK is available.

**Comment by SachinGanesh** [comment]
This is not an issue with the plugin. Something to do with your network connection? Seems like SSL issue. Have you tried downloading in different PC/network?

try running the below command and see if you get **file.zip**
``` 
/usr/bin/curl -f -L -o file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.8.0.zip --create-dirs --netrc-optional
```

**Comment by ch-muhammad-adil** [comment]
Hello Sachin, Yes I agree now it is not working for me. Can you please guide me what else can be done for this issue?
