### ISSUE TITLE
i Found bug in iOS. See below detailed resolution.

### ISSUE THREAD

**Issue by dharmesh304** [dreamsoftin/facebook_audience_network#41]
File FacebookAudienceNetworkInterstitialAd.swift
Line no:- 106
 `func interstitialAdDidClose(_ interstitialAd: FBInterstitialAd) {
        print("InterstitialAdView > interstitialAdDidClose")
     // You need to forgot dismissed event.
    //Here is the code you need to add 
        let placement_id: String = interstitialAd.placementID
        let invalidated: Bool = interstitialAd.isAdValid
        let arg: [String: Any] = [
            FANConstant.PLACEMENT_ID_ARG: placement_id,
            FANConstant.INVALIDATED_ARG: invalidated,
        ]
        self.channel.invokeMethod(FANConstant.DISMISSED_METHOD, arguments: arg)
    }
`

 Second Bug
Function Line No:- 48
func showAD(_ call: FlutterMethodCall) -> Bool {
// You need to comment line no 56 in this function. because you wrote two time.it will cause error while displaying ads second time. because ad was  not loaded. 
} 

Resolved full function

`func showAD(_ call: FlutterMethodCall) -> Bool {
        if !self.interstitialAd.isAdValid {
            print("FacebookAudienceNetworkInterstitialAdPlugin > showAD > not AdVaild")
            return false
        }
        let args: NSDictionary = call.arguments as! NSDictionary
        let delay: Int = args["delay"] as! Int
        //MARK:- Need to remove because already called below using delay
        //self.interstitialAd.show(fromRootViewController: UIApplication.shared.keyWindow?.rootViewController)
        
        print("@@@ delay %d", delay)
        
        if 0 < delay {
            let time = DispatchTime.now() + .seconds(delay)
            DispatchQueue.main.asyncAfter(deadline: time) {
                self.interstitialAd.show(fromRootViewController: UIApplication.shared.keyWindow?.rootViewController)
            }
        } else {
            self.interstitialAd.show(fromRootViewController: UIApplication.shared.keyWindow?.rootViewController)
        }
        return true
    }`

**Comment by SachinGanesh** [comment]
Thank you for letting us know. It would be great if you could raise a PR

**Comment by dharmesh304** [comment]
I had raised a PR Please check.

**Comment by SachinGanesh** [comment]
Merged. Thank you for your contribution!
