### ISSUE TITLE
Banner ad not update automatically

### ISSUE THREAD

**Issue by therichiekumar** [dreamsoftin/facebook_audience_network#43]
Like Google Admob , FAN banner ads not update automatically.
Here some insights
Admob Impression - 1284
FAN Impression - 57

**Comment by SachinGanesh** [comment]
> Ad refresh is not supported by Facebook Audience Network.

[https://developers.facebook.com/docs/audience-network/support/faq/](https://developers.facebook.com/docs/audience-network/support/faq/)

You can refer this https://github.com/dreamsoftin/facebook_audience_network/issues/28
