### ISSUE TITLE
 error: module 'facebook_audience_network' not found

### ISSUE THREAD

**Issue by theeomm** [dreamsoftin/facebook_audience_network#46]
I'm getting this error whenever I try to build or run the app.

```bash
1 error generated.
    /Users/-/-/-/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal
    error: module 'facebook_audience_network' not found
    @import facebook_audience_network;
```

**Comment by theeomm** [comment]
Fixed it after a couple of search and referring to other package. The problem came up because I had manually ran pod init and pod install.

**Comment by Pang654** [comment]
HI, 
May I know how to fix this error? I am facing the same error 
Thanks
