### ISSUE TITLE
Native banner for iOS

### ISSUE THREAD

**Issue by appycamper** [dreamsoftin/facebook_audience_network#47]
I tried adding native banner for iOS but not receiving any ads. Is this currently supported? Using v0.6.2

```
FacebookNativeAd(
                placementId: AdProvider.nativeBannerId,
                adType: NativeAdType.NATIVE_BANNER_AD,
                bannerAdSize: NativeBannerAdSize.HEIGHT_50,
                height: AdProvider.bannerHeight,
                width: double.infinity,
                backgroundColor: TGColors.adGray,
                titleColor: TGColors.gray,
                descriptionColor: TGColors.gray,
                buttonTitleColor: Colors.white,
                buttonColor: TGColors.darkBlue,
                buttonBorderColor: TGColors.darkBlue,
                expandAnimationDuraion: 200,
                keepExpandedWhileLoading: false,
              ),
```

**Comment by SachinGanesh** [comment]
Try with Test ID's

**Comment by appycamper** [comment]
I've added my iPhone's Identifier for Advertising (IDFA) as explained [here](https://developers.facebook.com/docs/audience-network/guides/test)

How do you obtain the hashed id for testing for iOS devices? they only show up on Android so I have nothing to put in as testingId 

```
FacebookAudienceNetwork.init(
  testingId: "what do you put here for iOS devices"
);
```

**Comment by SachinGanesh** [comment]
Replace your PLACEMENT_ID with IMG_16_9_APP_INSTALL#PLACEMENT_ID. You should get test ads.

Follow the instructions in this link to test the ads: https://developers.facebook.com/docs/audience-network/guides/test/inserted-code/

**Comment by mhle** [comment]
Thanks, the issue was using 
'''
keepExpandedWhileLoading: false
'''
does not work for iOS, as the result will be a white area where the banner should show up. 

After removing that line, the test banner showed up correctly.

Hope you can update the docs accordingly.

**Comment by appycamper** [comment]
@mhle Thanks that works! @SachinGanesh are you aware the stylings for native banner on iOS does not work? For example 
```
backgroundColor: Colors.green
```
does not work. It works on Android though.
