### ISSUE TITLE
Please bump Facebook SDK Version

### ISSUE THREAD

**Issue by johnmollaghan** [dreamsoftin/facebook_audience_network#48]
Hi there,

The current version of the SDK is quite old and there have been a lot of changes since 5.7.

Could you please bump the version of the Facebook SDK to the latest version?

It is now  5.10.0.

Thanks.

**Comment by Idan-BM** [comment]
Please update to 5.10.0 @SachinGanesh

**Comment by SachinGanesh** [comment]
release version 0.7.0
