### ISSUE TITLE
iOS build failing

### ISSUE THREAD

**Issue by leonardoj-cit** [dreamsoftin/facebook_audience_network#50]
I am having trouble building my project after adding the integration in iOs on Android, everything works fine, but when trying to build for iOS I get this:

```
  /dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_audience_network-0.6.2/ios/Classes/FacebookAudienceNetworkPlugin.m:2:9: fatal error:
    'facebook_audience_network/facebook_audience_network-Swift.h' file not found
    #import <facebook_audience_network/facebook_audience_network-Swift.h>
```

Any ideas?

**Comment by SachinGanesh** [comment]
As a temporary workaround, clone the repo and change FacebookAudienceNetworkPlugin.m file (line:2)

#import "FacebookAudienceNetworkPlugin.h"
// #import <facebook_audience_network/facebook_audience_network-Swift.h>
#import "facebook_audience_network-Swift.h"

**Comment by Pang654** [comment]
Hi, 
I am getting this error from building ios:

```
/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal
    error: module 'facebook_audience_network' not found
    @import facebook_audience_network;
```

Does anyone know how to solve it? Thanks

**Comment by john990** [comment]
> Hi,
> I am getting this error from building ios:
> 
> ```
> /ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal
>     error: module 'facebook_audience_network' not found
>     @import facebook_audience_network;
> ```
> 
> Does anyone know how to solve it? Thanks

I have same error too!  Are you fixed this?
