### ISSUE TITLE
Error installing FBAudienceNetwork

### ISSUE THREAD

**Issue by AmeerEbrahim** [dreamsoftin/facebook_audience_network#55]
pod intsall 
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (5.9.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/3b/h8gsb_ss03ndfm49x4ydb9pr0000gn/T/d20200804-23451-fe4ly4/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.9.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- 0:00:03 --:--:-- 0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries
Warning: left.
0 0 0 0 0 0 0 0 --:--:-- 0:00:02 --:--:-- 0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries
Warning: left.
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (22) The requested URL returned error: 500

**Comment by SachinGanesh** [comment]
This is mostly an issue with your network. Please check this https://github.com/dreamsoftin/facebook_audience_network/issues/40#issuecomment-657236519

**Comment by AmeerEbrahim** [comment]
It cannot be the issue of the network I suppose. Rest of the packages are getting installed without any issue. And referring to your issue40 #40 I ran the command which you gave for acquiring the .zip file and it gave an error " The requested URL returned error: 500  ".

**Comment by nimdanet** [comment]
I'm having the same error as @AmeerEbrahim  but with FBAudienceNetwork-6.6.0.zip. Same logs and all. I did the [#40 (comment)](https://github.com/dreamsoftin/facebook_audience_network/issues/40#issuecomment-657236519) and has the same error as @AmeerEbrahim : The requested URL returned error: 500 

I can't even download it via browser. It shows me a page "Sorry, something went wrong.". The "funny" part is that I sent the link to my friend and he was able to download it via browser so it seems some problem with my network. Is there anything I should try to track this issue?

**Comment by nimdanet** [comment]
For someone reaching this far on this problem, in my case was an instability on Facebook side. I just ran pod install after a couple hours and it worked. I didn't do nothing different, just waited.
