### ISSUE TITLE
Ads not showing after Publishing app on Play store?

### ISSUE THREAD

**Issue by abdullah432** [dreamsoftin/facebook_audience_network#67]
I test ads on debug mode and release mode. They are appearing but after publishing app on play store. Ads are not showing now. The purpose of posting this issue here is this post: https://community.kodular.io/t/not-showing-facebook-ads/30608
"After I contact to Facebook, they told me to integrate latest version of audiance network sdk.". Does this plugin use previous sdk version or everything is fine? Ads will start appearing after some days?

**Comment by SachinGanesh** [comment]
Hi, it may take up to 24 hours to get the ads.
