### ISSUE TITLE
Update SDK version to 6.0 for iOS

### ISSUE THREAD

**Issue by fadhlisulaimi** [dreamsoftin/facebook_audience_network#69]
Hi,

There is a new SDK version for facebook audience network for iOS.
This addresses the iOS 14 support and what not.

https://developers.facebook.com/docs/audience-network/changelog-ios/

**Comment by ZiaUrRahmam** [comment]
yes please update it to the latest version

**Comment by SachinGanesh** [comment]
Uploaded version 0.8.0 with the latest SDK
