### ISSUE TITLE
Update it to latest  Facebook ads SDK version 6.2

### ISSUE THREAD

**Issue by ZiaUrRahmam** [dreamsoftin/facebook_audience_network#79]
its been a long time when this package was updated.
Now facebook has released latest version of FB ads SDK 
So please update it as soon as possible.
@SachinGanesh @SurajShettigar @rilindnuka @dharmesh304 @Idan-BM  @dipinarora9 @BugsBunnyBR @dsi.dev

**Comment by dipinarora9** [comment]
Instream Video Ads are no longer available in Audience Network. 
Read more here: https://www.facebook.com/business/help/645132129564436?id=211412110064838

**Comment by ZiaUrRahmam** [comment]
@dipinarora9 what about sdk update?

**Comment by dipinarora9** [comment]
@ZiaUrRahmam the pull request is regarding the same

**Comment by ZiaUrRahmam** [comment]
@dipinarora9 ok waiting for better days.

**Comment by SachinGanesh** [comment]
Uploaded version 0.8.0 with latest SDK
