### ISSUE TITLE
Cant run on ios device

### ISSUE THREAD

**Issue by Encoder01** [dreamsoftin/facebook_audience_network#82]
`Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (6.2.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/v_/k__n0pt939zgw2256b3lntwh0000gp/T/d20201219-28892-4qjf6r/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-6.2.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 
`
when i say pod install i get this error message

**Comment by SachinGanesh** [comment]
Issue not related to the plugin
