### ISSUE TITLE
Facebook Audience Network SDK 6.2.1

### ISSUE THREAD

**Issue by lecatalan234** [dreamsoftin/facebook_audience_network#92]
Hello,
Facebook has released latest version of FAN SDK In order to monetize on iOS 14 once Apple introduces its new requirements.
So please update it as soon as possible.
Best regards.

**Comment by thevishvajeet** [comment]
Yes update is needed thanks in advance..

**Comment by SachinGanesh** [comment]
Package updated to latest SDK.
